server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: ${DATA_URL}
    username: ${DATA_USER}
    password: ${DATA_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    my.code.auth: INFO
